#ifndef _ASCURPIC_H_
# define _ASCURPIC_H_

# include <stdlib.h>
# include <stdio.h>
# include <unistd.h>
# include "bitmap.h"

/* Default values */
# define DEF_FONTSIZE	8
# define DEF_NBCHARPX	2
# define DEF_BGCOLOR	0xFFFFFF

/* Usage */
# define USAGE		"Usage: %s -f <filename> -t <filename> "	\
			"-o <filename> "				\
			"[-s <num> -n <num> -c <num>]\n\n"		\
			" -f <filename> \tBitmap to convert. "		\
			"This parameter needs the -t and -o ones.\n"	\
			" -t <filename> \tFile with some text to use\n"	\
			" -o <filename> \tThe Web Page you want "	\
			"to generate\n"					\
			" -s <num> \tFont size (in px)\n"		\
			" -n <num> \tNumber of char for 1px\n"		\
			" -c <color> \tBackground color in hex"		\
			" (e.g. : -c a0b1c2)\n"

/* Errors */
# define ERR_OPEN	"Unable to open %s\n"
# define ERR_BMP	"Invalid bitmap file\n"
# define ERR_MALLOC	"Could not perform malloc of %d bytes\n"

/* General parameters */
typedef struct
{
  t_bitmap		*input_bitmap;
  FILE			*input_text;
  FILE			*output_file;
  int			fontsize;
  int			nbcharpx;
  int			bgcolor;
}			param_t;

/* HTML Output */
# define HTML_HEADER	"<html>\n"					\
			"\t<head>\n"					\
			"\t\t<meta http-equiv=\"Content-Type\" "	\
			"content=\"text/html; charset=UTF-8\" />\n"	\
			"\t\t<title>Generated by AscUrPic</title>\n"	\
			"\t</head>\n"
# define HTML_INITBODY	"<body style=\"background-color:#%06x\">"	\
			"<pre style=\"font-size:%dpx\">\n"

# define HTML_SPAN_C_1	"<span style=\"color:#%06x;\">%s"
# define HTML_SPAN_C_2	"</span>"
# define HTML_END	"</span>\n</pre></body>\n</html>\n"

/* Prototypes */
void			disp_info_bmp(t_bitmap *bmp);
int			parse_opts(param_t *p, int ac, char **av);
void			write_page(param_t *p);
void			*xmalloc(int size);

#endif /* !_ASCURPIC_H_ */
